### ISSUE TITLE
Google 搜索无法使用了

### ISSUE THREAD

**Issue by Po-hsin** [wanghsinche/GM_scripts#2]
Google 搜索无法使用了，是百度把谷歌的自定义搜索禁了还是什么？

error code : 
Refused to connect to "https://www.googleapis.com/customsearch/v1element?key=AIzaSyCVAXiUzRYsML1Pv…c9e9dba5eea831d506e69a&cx=018177143380893153305:yk0qpgydx_e&q=test&start=0": URL was permanently blocked by the user

**Comment by wanghsinche** [comment]
你的url复制错了？脚本安装后没出现这个问题啊，工作正常
